### ISSUE TITLE
[Whisper-Faster_r160.5_windows]: --large or --large-v3 shows error

### ISSUE THREAD

**Issue by Milincho** [Purfview/whisper-standalone-win#110]
[Whisper-Faster_r160.5_windows]

Using using --large or --large-v3 shows error: 

Model not found at: c:\Program Files\Whisper-Faster\_models\faster-whisper-large-v3-fp16
Attempting to download:

Traceback (most recent call last):
  File "D:\whisper-fast\__main__.py", line 704, in <module>
  File "D:\whisper-fast\__main__.py", line 443, in cli
  File "faster_whisper\utils.py", line 196, in download_model
ValueError: Invalid model size 'large-v3-fp16', expected one of: tiny.en, tiny, base.en, base, small.en, small, medium.en, medium, large-v1, large-v2, large-v3, large
[22148] Failed to execute script '__main__' due to unhandled exception!

**Comment by Purfview** [comment]
Autodownload for large-v3 should be fixed in `r160.6`. Thanks for the report!
