### ISSUE TITLE
Crash when batch processing reaches video file without Audio

### ISSUE THREAD

**Issue by Echo51** [Purfview/whisper-standalone-win#280]
Hi,

I process a large amount of short .mp4 videos downloaded from the internet, via the *.mp4 wildcard for inputting many files.
However when this reaches an .mp4 with no audio track, it crashes

Output:
`Starting work on: .\videos\BoY9gBFAJYm, 2018-10-01.mp4

Traceback (most recent call last):
  File "D:\whisper-fast\_XXL\__main__.py", line 1668, in <module>
  File "D:\whisper-fast\_XXL\__main__.py", line 1552, in cli
  File "faster_whisper\transcribe.py", line 319, in transcribe
  File "faster_whisper\audio.py", line 52, in decode_audio
  File "faster_whisper\audio.py", line 103, in _resample_frames
  File "faster_whisper\audio.py", line 90, in _group_frames
  File "faster_whisper\audio.py", line 80, in _ignore_invalid_frames
  File "av\\container\\input.pyx", line 211, in decode
  File "av\\container\\input.pyx", line 142, in demux
  File "av\\container\\streams.pyx", line 117, in av.container.streams.StreamContainer.get
IndexError: tuple index out of range
[3292] Failed to execute script '__main__' due to unhandled exception!`

Thanks for an amazing piece of software otherwise!

**Comment by Purfview** [comment]
Try `--check_files`

**Comment by Echo51** [comment]
Thanks, that did it! Didn't think to look through the commandlist first, sorry!
