### ISSUE TITLE
cudaErrorNoKernelImageForDevice: no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by Connum** [Purfview/whisper-standalone-win#314]
This is what I get on my **NVIDIA GeForce GTX 980 Ti**. Latest CUDA is installed.

```cmd
D:\AI\Faster-Whisper-XXL_r192.3.4_windows\Faster-Whisper-XXL>faster-whisper-xxl.exe --language de "01-Speaker 1-67.wav"

Standalone Faster-Whisper-XXL r192.3.4 running on: CUDA


Starting work on: 01-Speaker 1-67.wav

Traceback (most recent call last):
  File "D:\whisper-fast\_XXL\__main__.py", line 1668, in <module>
  File "D:\whisper-fast\_XXL\__main__.py", line 1595, in cli
  File "faster_whisper\transcribe.py", line 1456, in restore_speech_timestamps
  File "faster_whisper\transcribe.py", line 798, in generate_segments
  File "faster_whisper\transcribe.py", line 1109, in encode
RuntimeError: parallel_for failed: cudaErrorNoKernelImageForDevice: no kernel image is available for execution on the device
[45748] Failed to execute script '__main__' due to unhandled exception!
```

**Comment by techguru0** [comment]
980ti I believe to to old for this

**Comment by sn260591** [comment]
See https://github.com/SYSTRAN/faster-whisper/issues/806

**Comment by Purfview** [comment]
> This is what I get on my **NVIDIA GeForce GTX 980 Ti**. 

Post what NVIDIA driver version you have installed.

**Comment by Purfview** [comment]
1) Try to replace these files -> [CTranslate2_Compute Capability_5.0.zip](https://github.com/user-attachments/files/17526742/CTranslate2_Compute.Capability_5.0.zip)

2) Or use older version ->`Faster-Whisper r192.3`

3) Or don't run on CUDA -> `--device "cpu"`
