### ISSUE TITLE
IndexError: list index out of range errors

### ISSUE THREAD

**Issue by ClaireCJS** [Purfview/whisper-standalone-win#317]
I'm wondering why I get these errors when I run ```whisper-faster-xxl.exe```

Particularly since I don't have a ``d:\whisper-fast\_XXL``` folder

They happen... for certain songs (1 out of 10-15), but not for others.

I can't say the exact cause, that i also can't fathom why it would be referencing a folder that doesn't exist on my D: drive ...

```
Transcription speed: 6.66 audio seconds/s

Traceback (most recent call last):
  File "D:\whisper-fast\_XXL\__main__.py", line 1668, in <module>
  File "D:\whisper-fast\_XXL\__main__.py", line 1652, in cli
  File "D:\whisper-fast\_XXL\__main__.py", line 320, in __call__
  File "D:\whisper-fast\_XXL\__main__.py", line 859, in write_result
  File "D:\whisper-fast\_XXL\__main__.py", line 802, in iterate_result_alt
  File "D:\whisper-fast\_XXL\__main__.py", line 785, in iterate_subtitles_alt
IndexError: list index out of range
[17684] Failed to execute script '__main__' due to unhandled exception!
```

**Comment by Purfview** [comment]
Dupe of https://github.com/Purfview/whisper-standalone-win/issues/282
