### ISSUE TITLE
Error with longer transcripts

### ISSUE THREAD

**Issue by mmb78** [Purfview/whisper-standalone-win#329]
When transcribing longer audio, not all the output files will be generated and this error will be shown:

Traceback (most recent call last):
  File "D:\whisper-fast\_XXL\__main__.py", line 1765, in <module>
  File "D:\whisper-fast\_XXL\__main__.py", line 1732, in cli
  File "D:\whisper-fast\_XXL\__main__.py", line 933, in write_all
  File "D:\whisper-fast\_XXL\__main__.py", line 365, in __call__
  File "D:\whisper-fast\_XXL\__main__.py", line 386, in write_result
PermissionError: [Errno 13] Permission denied
[20292] Failed to execute script '__main__' due to unhandled exception!

This was run with these parameters:
faster-whisper-xxl.exe audiotrack.m4a -l en -m large-v3-turbo -f all --beep_off -pp -ct float16 --diarize -o m:\_Temp\

**Comment by Purfview** [comment]
That's when writing "audiotrack.text" file, probably you had opened it and didn't closed the program, close it then try again.
