### ISSUE TITLE
SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate

### ISSUE THREAD

**Issue by mark05e** [Purfview/whisper-standalone-win#75]
Issue: Model fails to download behind proxy
```
Model not found at: C:\Temp\onw-eng\_models\faster-whisper-medium
Attempting to download:

An error occured while synchronizing the model guillaumekln/faster-whisper-medium from the Hugging Face Hub:
(MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /api/models/guillaumekln/faster-whisper-medium/revision/main (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))"), '(Request ID: 28ac8c1a-a40a-477d-b707-9cc72b32ec1f)')
Trying to load the model directly from the local cache, if it exists.
Standalone Faster-Whisper r153 running on: CUDA

Traceback (most recent call last):
  File "D:\whisper-fast\__main__.py", line 655, in <module>
  File "D:\whisper-fast\__main__.py", line 537, in cli
  File "faster_whisper\transcribe.py", line 129, in __init__
RuntimeError: Unable to open file 'model.bin' in model 'C:\Temp\onw-eng\.cache\hub\models--guillaumekln--faster-whisper-medium\snapshots\8701f851d407f3f47e091bb13b8dac5290c7f7fb'
[25088] Failed to execute script '__main__' due to unhandled exception!
```

Related: https://github.com/Purfview/whisper-standalone-win/issues/59

**Comment by mark05e** [comment]
Resolution: _To address this error, set the environment variable `REQUESTS_CA_BUNDLE` to the path of CA bundle certificate file in PEM format._

REQUESTS_CA_BUNDLE="C:\Users\xxxx\cacert-with-corp-proxy-cert.pem"

References: 
- https://learn.microsoft.com/en-us/cli/azure/use-cli-effectively?tabs=bash%2Cbash2#work-behind-a-proxy
- https://github.com/Azure/azure-cli/issues/5099#issuecomment-355047982

**Comment by Purfview** [comment]
As I understand that is a local problem  and it's not an universal solution, no?

**Comment by mark05e** [comment]
This is for computers that are behind a type of proxy that requires usage of non-standard certificates or maybe disabling certificate validation. While I'm not sure of the specifics, I think it's a common practice in these scenarios - for projects that use the [Python Requests library](https://requests.readthedocs.io/en/latest/user/advanced/).

**Comment by Purfview** [comment]
> disabling certificate validation

You need to ask `huggingface_hub` for such option -> https://github.com/huggingface/huggingface_hub/issues/1691

**Comment by Wauplin** [comment]
Hi there, maintainer of `huggingface_hub` here :wave: (just saw https://github.com/huggingface/huggingface_hub/issues/1691)

Setting proxy can be done using the `HTTP_PROXY` and `HTTPS_PROXY` environment variables (see https://requests.readthedocs.io/en/latest/user/advanced/#proxies). Otherwise, it's possible to configure your own `requests.Session` object that will be reuse by `huggingface_hub` using [`configure_http_backend`](https://huggingface.co/docs/huggingface_hub/package_reference/utilities#huggingface_hub.configure_http_backend). Configuring your own Session gives you a fine-grained solution to set your own behavior instead of passing args like `verify=False` to everywhere methods. Hope this will help you solve your issue.

**Comment by Purfview** [comment]
Hi @Wauplin

This repo is aimed at the common users and provides only a frozen .exe, I only could provide the users a new arg to be able to pass `verify=False` there:

https://github.com/guillaumekln/faster-whisper/blob/5a0541ea7d054aa3716ac492491de30158c20057/faster_whisper/utils.py#L98C16-L98C31

PS
Let's ping the dev of `faster-whisper` for his opinion: @guillaumekln

**Comment by mark05e** [comment]
Hi @Purfview, I apologize for the confusion. To clarify, there is no issue with the code. This is simply a matter of documentation and information. There's no need to take action on the code. I hope this helps!I've found examples of how Azure CLI[1] and Conda[2] address this issue in their documentation

1 - https://learn.microsoft.com/en-us/cli/azure/use-cli-effectively?tabs=bash%2Cbash2#work-behind-a-proxy
2 - https://docs.conda.io/projects/conda/en/latest/user-guide/configuration/non-standard-certs.html

**Comment by Purfview** [comment]
> There's no need to take action on the code. 

Do you mean that you don't get this error when exe is used in Command Prompt?

**Comment by mark05e** [comment]
I do get the error. But that is because of the proxy/certificate thing I have on my machine. There are documentations available on other projects on how to work with this.

**Comment by Purfview** [comment]
Still a simple fallback with `verify=False` in code would be the most user-friendly solution.

**Comment by mark05e** [comment]
In that case, I think a descriptive switch would be nice. Something like `requests_verify=false`

**Comment by Purfview** [comment]
With a fallback that would be automatic, but first this needs to be implementad at `huggingface_hub`. :)

**Comment by Wauplin** [comment]
To implement a `verify=False`-feature right now with the current implementation, one has to use the configure_http_backend as described in https://github.com/Purfview/whisper-standalone-win/issues/75#issuecomment-1733257814. It's possible to call it at runtime anytime (doesn't have to be at start-up like a monkeypatch). I don't know how your exe works but if you have a button or tick box, you can propagate that to call configure_http_backend _before_ making the actual requests to the Hub. This way we avoid adding a `verify: bool` kwarg to each and every method of `huggingface_hub`.

**Comment by Purfview** [comment]
@mark05e  Check this test build if you get the error -> https://we.tl/t-MosRHbwycn

**Comment by mark05e** [comment]
Sorry for the delay. My current proxy is blocking access to wetransfer. Trying to get access to another machine without proxy to download this.

**Comment by Purfview** [comment]
https://github.com/Purfview/whisper-standalone-win/releases/download/faster-whisper/Whisper-Faster_test.zip

**Comment by mark05e** [comment]
Try to transcribe initially

```
PS C:\Temp\onw-eng\test> .\whisper-faster.exe "C:\Temp\onw-eng\wavs\root\*.WAV" --language=English --model=medium --output_format text --batch_recursive

Model not found at: C:\Temp\onw-eng\test\_models\faster-whisper-medium
Attempting to download:

An error occured while synchronizing the model guillaumekln/faster-whisper-medium from the Hugging Face Hub:
(MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /api/models/guillaumekln/faster-whisper-medium/revision/main (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))"), '(Request ID: 004d111c-72ae-4ed2-a067-37ea453d8d0f)')
Trying to load the model directly from the local cache, if it exists.
Traceback (most recent call last):
  File "urllib3\connectionpool.py", line 670, in urlopen
  File "urllib3\connectionpool.py", line 381, in _make_request
  File "urllib3\connectionpool.py", line 978, in _validate_conn
  File "urllib3\connection.py", line 362, in connect
  File "urllib3\util\ssl_.py", line 386, in ssl_wrap_socket
  File "ssl.py", line 500, in wrap_socket
  File "ssl.py", line 1040, in _create
  File "ssl.py", line 1309, in do_handshake
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests\adapters.py", line 486, in send
  File "urllib3\connectionpool.py", line 726, in urlopen
  File "urllib3\util\retry.py", line 446, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /api/models/guillaumekln/faster-whisper-medium/revision/main (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "faster_whisper\utils.py", line 214, in download_model
  File "huggingface_hub\utils\_validators.py", line 118, in _inner_fn
  File "huggingface_hub\_snapshot_download.py", line 186, in snapshot_download
  File "huggingface_hub\utils\_validators.py", line 118, in _inner_fn
  File "huggingface_hub\hf_api.py", line 1868, in repo_info
  File "huggingface_hub\utils\_validators.py", line 118, in _inner_fn
  File "huggingface_hub\hf_api.py", line 1677, in model_info
  File "requests\sessions.py", line 600, in get
  File "requests\sessions.py", line 587, in request
  File "requests\sessions.py", line 701, in send
  File "huggingface_hub\utils\_http.py", line 63, in send
  File "requests\adapters.py", line 517, in send
requests.exceptions.SSLError: (MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /api/models/guillaumekln/faster-whisper-medium/revision/main (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))"), '(Request ID: 004d111c-72ae-4ed2-a067-37ea453d8d0f)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\whisper-fast\__main__.py", line 655, in <module>
  File "D:\whisper-fast\__main__.py", line 401, in cli
  File "faster_whisper\utils.py", line 230, in download_model
  File "huggingface_hub\utils\_validators.py", line 118, in _inner_fn
  File "huggingface_hub\_snapshot_download.py", line 169, in snapshot_download
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Temp\\onw-eng\\test\\.cache\\hub\\models--guillaumekln--faster-whisper-medium\\refs\\main'
[3296] Failed to execute script '__main__' due to unhandled exception!
```

Then I try switches --verify=false and --requests_verify=false, does not work

```
PS C:\Temp\onw-eng\test> .\whisper-faster.exe "C:\Temp\onw-eng\wavs\root\*.WAV" --language=English --model=medium --output_format text --batch_recursive --verify=false
usage: whisper-faster.exe [-h] [--model MODEL] [--model_dir MODEL_DIR] [--device DEVICE] [--output_dir OUTPUT_DIR] [--output_format {lrc,txt,text,vtt,srt,tsv,json,all}] [--verbose VERBOSE]
                          [--task {transcribe,translate}]
                          [--language {af,am,ar,as,az,ba,be,bg,bn,bo,br,bs,ca,cs,cy,da,de,el,en,es,et,eu,fa,fi,fo,fr,gl,gu,ha,haw,he,hi,hr,ht,hu,hy,id,is,it,ja,jw,ka,kk,km,kn,ko,la,lb,ln,lo,lt,lv,mg,mi,mk,ml,mn,mr,ms,mt,my,ne,nl,nn,no,oc,pa,pl,ps,pt,ro,ru,sa,sd,si,sk,sl,sn,so,sq,sr,su,sv,sw,ta,te,tg,th,tk,tl,tr,tt,uk,ur,uz,vi,yi,yo,zh,Afrikaans,Albanian,Amharic,Arabic,Armenian,Assamese,Azerbaijani,Bashkir,Basque,Belarusian,Bengali,Bosnian,Breton,Bulgarian,Burmese,Castilian,Catalan,Chinese,Croatian,Czech,Danish,Dutch,English,Estonian,Faroese,Finnish,Flemish,French,Galician,Georgian,German,Greek,Gujarati,Haitian,Haitian Creole,Hausa,Hawaiian,Hebrew,Hindi,Hungarian,Icelandic,Indonesian,Italian,Japanese,Javanese,Kannada,Kazakh,Khmer,Korean,Lao,Latin,Latvian,Letzeburgesch,Lingala,Lithuanian,Luxembourgish,Macedonian,Malagasy,Malay,Malayalam,Maltese,Maori,Marathi,Moldavian,Moldovan,Mongolian,Myanmar,Nepali,Norwegian,Nynorsk,Occitan,Panjabi,Pashto,Persian,Polish,Portuguese,Punjabi,Pushto,Romanian,Russian,Sanskrit,Serbian,Shona,Sindhi,Sinhala,Sinhalese,Slovak,Slovenian,Somali,Spanish,Sundanese,Swahili,Swedish,Tagalog,Tajik,Tamil,Tatar,Telugu,Thai,Tibetan,Turkish,Turkmen,Ukrainian,Urdu,Uzbek,Valencian,Vietnamese,Welsh,Yiddish,Yoruba}]
                          [--temperature TEMPERATURE] [--best_of BEST_OF] [--beam_size BEAM_SIZE] [--patience PATIENCE] [--length_penalty LENGTH_PENALTY] [--repetition_penalty REPETITION_PENALTY]
                          [--no_repeat_ngram_size NO_REPEAT_NGRAM_SIZE] [--suppress_tokens SUPPRESS_TOKENS] [--initial_prompt INITIAL_PROMPT] [--condition_on_previous_text CONDITION_ON_PREVIOUS_TEXT]
                          [--prompt_reset_on_temperature PROMPT_RESET_ON_TEMPERATURE] [--temperature_increment_on_fallback TEMPERATURE_INCREMENT_ON_FALLBACK]
                          [--compression_ratio_threshold COMPRESSION_RATIO_THRESHOLD] [--logprob_threshold LOGPROB_THRESHOLD] [--no_speech_threshold NO_SPEECH_THRESHOLD] [--no_speech_strict_lvl {0,1,2}]
                          [--word_timestamps WORD_TIMESTAMPS] [--highlight_words HIGHLIGHT_WORDS] [--prepend_punctuations PREPEND_PUNCTUATIONS] [--append_punctuations APPEND_PUNCTUATIONS] [--threads THREADS]
                          [--version] [--vad_filter VAD_FILTER] [--vad_threshold VAD_THRESHOLD] [--vad_min_speech_duration_ms VAD_MIN_SPEECH_DURATION_MS]
                          [--vad_max_speech_duration_s VAD_MAX_SPEECH_DURATION_S] [--vad_min_silence_duration_ms VAD_MIN_SILENCE_DURATION_MS] [--vad_speech_pad_ms VAD_SPEECH_PAD_MS]
                          [--vad_window_size_samples VAD_WINDOW_SIZE_SAMPLES] [--compute_type {default,auto,int8,int8_float16,int8_float32,int8_bfloat16,int16,float16,float32,bfloat16}] [--batch_recursive]
                          [--beep_off] [--skip] [--checkcuda] [--print_progress]
                          audio [audio ...]
whisper-faster.exe: error: unrecognized arguments: --verify=false
```

Help page
```
PS C:\Temp\onw-eng\test> .\whisper-faster.exe --help
usage: whisper-faster.exe [-h] [--model MODEL] [--model_dir MODEL_DIR] [--device DEVICE] [--output_dir OUTPUT_DIR]
                          [--output_format {lrc,txt,text,vtt,srt,tsv,json,all}] [--verbose VERBOSE]
                          [--task {transcribe,translate}]
                          [--language {af,am,ar,as,az,ba,be,bg,bn,bo,br,bs,ca,cs,cy,da,de,el,en,es,et,eu,fa,fi,fo,fr,gl,gu,ha,haw,he,hi,hr,ht,hu,hy,id,is,it,ja,jw,ka,kk,km,kn,ko,la,lb,ln,lo,lt,lv,mg,mi,mk,ml,mn,mr,ms,mt,my,ne,nl,nn,no,oc,pa,pl,ps,pt,ro,ru,sa,sd,si,sk,sl,sn,so,sq,sr,su,sv,sw,ta,te,tg,th,tk,tl,tr,tt,uk,ur,uz,vi,yi,yo,zh,Afrikaans,Albanian,Amharic,Arabic,Armenian,Assamese,Azerbaijani,Bashkir,Basque,Belarusian,Bengali,Bosnian,Breton,Bulgarian,Burmese,Castilian,Catalan,Chinese,Croatian,Czech,Danish,Dutch,English,Estonian,Faroese,Finnish,Flemish,French,Galician,Georgian,German,Greek,Gujarati,Haitian,Haitian Creole,Hausa,Hawaiian,Hebrew,Hindi,Hungarian,Icelandic,Indonesian,Italian,Japanese,Javanese,Kannada,Kazakh,Khmer,Korean,Lao,Latin,Latvian,Letzeburgesch,Lingala,Lithuanian,Luxembourgish,Macedonian,Malagasy,Malay,Malayalam,Maltese,Maori,Marathi,Moldavian,Moldovan,Mongolian,Myanmar,Nepali,Norwegian,Nynorsk,Occitan,Panjabi,Pashto,Persian,Polish,Portuguese,Punjabi,Pushto,Romanian,Russian,Sanskrit,Serbian,Shona,Sindhi,Sinhala,Sinhalese,Slovak,Slovenian,Somali,Spanish,Sundanese,Swahili,Swedish,Tagalog,Tajik,Tamil,Tatar,Telugu,Thai,Tibetan,Turkish,Turkmen,Ukrainian,Urdu,Uzbek,Valencian,Vietnamese,Welsh,Yiddish,Yoruba}]
                          [--temperature TEMPERATURE] [--best_of BEST_OF] [--beam_size BEAM_SIZE]
                          [--patience PATIENCE] [--length_penalty LENGTH_PENALTY]
                          [--repetition_penalty REPETITION_PENALTY] [--no_repeat_ngram_size NO_REPEAT_NGRAM_SIZE]
                          [--suppress_tokens SUPPRESS_TOKENS] [--initial_prompt INITIAL_PROMPT]
                          [--condition_on_previous_text CONDITION_ON_PREVIOUS_TEXT]
                          [--prompt_reset_on_temperature PROMPT_RESET_ON_TEMPERATURE]
                          [--temperature_increment_on_fallback TEMPERATURE_INCREMENT_ON_FALLBACK]
                          [--compression_ratio_threshold COMPRESSION_RATIO_THRESHOLD]
                          [--logprob_threshold LOGPROB_THRESHOLD] [--no_speech_threshold NO_SPEECH_THRESHOLD]
                          [--no_speech_strict_lvl {0,1,2}] [--word_timestamps WORD_TIMESTAMPS]
                          [--highlight_words HIGHLIGHT_WORDS] [--prepend_punctuations PREPEND_PUNCTUATIONS]
                          [--append_punctuations APPEND_PUNCTUATIONS] [--threads THREADS] [--version]
                          [--vad_filter VAD_FILTER] [--vad_threshold VAD_THRESHOLD]
                          [--vad_min_speech_duration_ms VAD_MIN_SPEECH_DURATION_MS]
                          [--vad_max_speech_duration_s VAD_MAX_SPEECH_DURATION_S]
                          [--vad_min_silence_duration_ms VAD_MIN_SILENCE_DURATION_MS]
                          [--vad_speech_pad_ms VAD_SPEECH_PAD_MS] [--vad_window_size_samples VAD_WINDOW_SIZE_SAMPLES]
                          [--compute_type {default,auto,int8,int8_float16,int8_float32,int8_bfloat16,int16,float16,float32,bfloat16}]
                          [--batch_recursive] [--beep_off] [--skip] [--checkcuda] [--print_progress]
                          audio [audio ...]

positional arguments:
  audio                 audio file(s). You can enter a file wildcard, filelist (txt. m3u, m3u8, lst) or directory to
                        do batch processing. Note: non-media files in list or directory are filtered out by extension.

optional arguments:
  -h, --help            show this help message and exit
  --model MODEL, -m MODEL
                        name of the Whisper model to use (default: medium)
  --model_dir MODEL_DIR
                        the path to save model files; uses C:\Temp\onw-eng\test\_models by default (default:
                        None)
  --device DEVICE, -d DEVICE
                        device to use (default: cuda)
  --output_dir OUTPUT_DIR, -o OUTPUT_DIR
                        directory to save the outputs. By default the same folder where the executable file is or
                        where media file is if --batch_recursive=True. '.'- sets to the current folder. 'source' -
                        sets to where media file is. (default: default)
  --output_format {lrc,txt,text,vtt,srt,tsv,json,all}, -f {lrc,txt,text,vtt,srt,tsv,json,all}
                        format of the output file; if not specified srt will be produced (default: srt)
  --verbose VERBOSE, -v VERBOSE
                        whether to print out debug messages (default: False)
  --task {transcribe,translate}
                        whether to perform X->X speech recognition ('transcribe') or X->English translation
                        ('translate') (default: transcribe)
  --language {af,am,ar,as,az,ba,be,bg,bn,bo,br,bs,ca,cs,cy,da,de,el,en,es,et,eu,fa,fi,fo,fr,gl,gu,ha,haw,he,hi,hr,ht,hu,hy,id,is,it,ja,jw,ka,kk,km,kn,ko,la,lb,ln,lo,lt,lv,mg,mi,mk,ml,mn,mr,ms,mt,my,ne,nl,nn,no,oc,pa,pl,ps,pt,ro,ru,sa,sd,si,sk,sl,sn,so,sq,sr,su,sv,sw,ta,te,tg,th,tk,tl,tr,tt,uk,ur,uz,vi,yi,yo,zh,Afrikaans,Albanian,Amharic,Arabic,Armenian,Assamese,Azerbaijani,Bashkir,Basque,Belarusian,Bengali,Bosnian,Breton,Bulgarian,Burmese,Castilian,Catalan,Chinese,Croatian,Czech,Danish,Dutch,English,Estonian,Faroese,Finnish,Flemish,French,Galician,Georgian,German,Greek,Gujarati,Haitian,Haitian Creole,Hausa,Hawaiian,Hebrew,Hindi,Hungarian,Icelandic,Indonesian,Italian,Japanese,Javanese,Kannada,Kazakh,Khmer,Korean,Lao,Latin,Latvian,Letzeburgesch,Lingala,Lithuanian,Luxembourgish,Macedonian,Malagasy,Malay,Malayalam,Maltese,Maori,Marathi,Moldavian,Moldovan,Mongolian,Myanmar,Nepali,Norwegian,Nynorsk,Occitan,Panjabi,Pashto,Persian,Polish,Portuguese,Punjabi,Pushto,Romanian,Russian,Sanskrit,Serbian,Shona,Sindhi,Sinhala,Sinhalese,Slovak,Slovenian,Somali,Spanish,Sundanese,Swahili,Swedish,Tagalog,Tajik,Tamil,Tatar,Telugu,Thai,Tibetan,Turkish,Turkmen,Ukrainian,Urdu,Uzbek,Valencian,Vietnamese,Welsh,Yiddish,Yoruba}, -l {af,am,ar,as,az,ba,be,bg,bn,bo,br,bs,ca,cs,cy,da,de,el,en,es,et,eu,fa,fi,fo,fr,gl,gu,ha,haw,he,hi,hr,ht,hu,hy,id,is,it,ja,jw,ka,kk,km,kn,ko,la,lb,ln,lo,lt,lv,mg,mi,mk,ml,mn,mr,ms,mt,my,ne,nl,nn,no,oc,pa,pl,ps,pt,ro,ru,sa,sd,si,sk,sl,sn,so,sq,sr,su,sv,sw,ta,te,tg,th,tk,tl,tr,tt,uk,ur,uz,vi,yi,yo,zh,Afrikaans,Albanian,Amharic,Arabic,Armenian,Assamese,Azerbaijani,Bashkir,Basque,Belarusian,Bengali,Bosnian,Breton,Bulgarian,Burmese,Castilian,Catalan,Chinese,Croatian,Czech,Danish,Dutch,English,Estonian,Faroese,Finnish,Flemish,French,Galician,Georgian,German,Greek,Gujarati,Haitian,Haitian Creole,Hausa,Hawaiian,Hebrew,Hindi,Hungarian,Icelandic,Indonesian,Italian,Japanese,Javanese,Kannada,Kazakh,Khmer,Korean,Lao,Latin,Latvian,Letzeburgesch,Lingala,Lithuanian,Luxembourgish,Macedonian,Malagasy,Malay,Malayalam,Maltese,Maori,Marathi,Moldavian,Moldovan,Mongolian,Myanmar,Nepali,Norwegian,Nynorsk,Occitan,Panjabi,Pashto,Persian,Polish,Portuguese,Punjabi,Pushto,Romanian,Russian,Sanskrit,Serbian,Shona,Sindhi,Sinhala,Sinhalese,Slovak,Slovenian,Somali,Spanish,Sundanese,Swahili,Swedish,Tagalog,Tajik,Tamil,Tatar,Telugu,Thai,Tibetan,Turkish,Turkmen,Ukrainian,Urdu,Uzbek,Valencian,Vietnamese,Welsh,Yiddish,Yoruba}
                        language spoken in the audio, specify None to perform language detection (default: None)
  --temperature TEMPERATURE
                        temperature to use for sampling (default: 0)
  --best_of BEST_OF, -bo BEST_OF
                        number of candidates when sampling with non-zero temperature (default: 5)
  --beam_size BEAM_SIZE, -bs BEAM_SIZE
                        number of beams in beam search, only applicable when temperature is zero (default: 5)
  --patience PATIENCE, -p PATIENCE
                        optional patience value to use in beam decoding, as in https://arxiv.org/abs/2204.05424, the
                        default (1.0) is equivalent to conventional beam search (default: 1.0)
  --length_penalty LENGTH_PENALTY
                        optional token length penalty coefficient (alpha) as in https://arxiv.org/abs/1609.08144, uses
                        simple length normalization by default (default: 1.0)
  --repetition_penalty REPETITION_PENALTY
                        Penalty applied to the score of previously generated tokens (set > 1.0 to penalize). (default:
                        1.0)
  --no_repeat_ngram_size NO_REPEAT_NGRAM_SIZE
                        Prevent repetitions of ngrams with this size (set 0 to disable). (default: 0)
  --suppress_tokens SUPPRESS_TOKENS
                        comma-separated list of token ids to suppress during sampling; '-1' will suppress most special
                        characters except common punctuations (default: -1)
  --initial_prompt INITIAL_PROMPT, -prompt INITIAL_PROMPT
                        optional text to provide as a prompt for the first window. (default: ,.?!)
  --condition_on_previous_text CONDITION_ON_PREVIOUS_TEXT
                        if True, provide the previous output of the model as a prompt for the next window; disabling
                        may make the text inconsistent across windows, but the model becomes less prone to getting
                        stuck in a failure loop (default: True)
  --prompt_reset_on_temperature PROMPT_RESET_ON_TEMPERATURE
                        Resets prompt if temperature is above this value. Arg has effect only if
                        condition_on_previous_text is True. (default: 0.5)
  --temperature_increment_on_fallback TEMPERATURE_INCREMENT_ON_FALLBACK
                        temperature to increase when falling back when the decoding fails to meet either of the
                        thresholds below. To disable fallback set it to 'None'. (default: 0.2)
  --compression_ratio_threshold COMPRESSION_RATIO_THRESHOLD
                        if the gzip compression ratio is higher than this value, treat the decoding as failed
                        (default: 2.4)
  --logprob_threshold LOGPROB_THRESHOLD
                        if the average log probability is lower than this value, treat the decoding as failed
                        (default: -1.0)
  --no_speech_threshold NO_SPEECH_THRESHOLD
                        if the probability of the <|nospeech|> token is higher than this value AND the decoding has
                        failed due to `logprob_threshold`, consider the segment as silence (default: 0.6)
  --no_speech_strict_lvl {0,1,2}
                        (experimental) Level of stricter actions when no_speech_prob > 0.93. Use beam_size=5 if this
                        is enabled. Options: 0 - Disabled (do nothing), 1 - Reset propmt (see
                        condition_on_previous_text), 2 - Invalidate the cached encoder output (if no_speech_threshold
                        is not None). Arg meant to combat cases where the model is getting stuck in a failure loop or
                        outputs nonsense (default: 0)
  --word_timestamps WORD_TIMESTAMPS, -wt WORD_TIMESTAMPS
                        (experimental) extract word-level timestamps and refine the results based on them (default:
                        True)
  --highlight_words HIGHLIGHT_WORDS, -hw HIGHLIGHT_WORDS
                        underline each word as it is spoken AKA karaoke in srt and vtt output formats (default: False)
  --prepend_punctuations PREPEND_PUNCTUATIONS
                        if word_timestamps is True, merge these punctuation symbols with the next word (default:
                        "'“¿([{-)
  --append_punctuations APPEND_PUNCTUATIONS
                        if word_timestamps is True, merge these punctuation symbols with the previous word (default:
                        "'.。,，!！?？:：”)]}、)
  --threads THREADS     number of threads used for CPU inference; By default number of the real cores but no more that
                        4 (default: 0)
  --version             Show Faster-Whisper's version number
  --vad_filter VAD_FILTER, -vad VAD_FILTER
                        Enable the voice activity detection (VAD) to filter out parts of the audio without speech.
                        (default: True)
  --vad_threshold VAD_THRESHOLD
                        Probabilities above this value are considered as speech. (default: 0.45)
  --vad_min_speech_duration_ms VAD_MIN_SPEECH_DURATION_MS
                        Final speech chunks shorter min_speech_duration_ms are thrown out. (default: 350)
  --vad_max_speech_duration_s VAD_MAX_SPEECH_DURATION_S
                        Maximum duration of speech chunks in seconds. Longer will be split at the timestamp of the
                        last silence. (default: None)
  --vad_min_silence_duration_ms VAD_MIN_SILENCE_DURATION_MS
                        In the end of each speech chunk time to wait before separating it. (default: 3000)
  --vad_speech_pad_ms VAD_SPEECH_PAD_MS
                        Final speech chunks are padded by speech_pad_ms each side. (default: 900)
  --vad_window_size_samples VAD_WINDOW_SIZE_SAMPLES
                        Size of audio chunks fed to the silero VAD model. Values other than 512, 1024, 1536 may affect
                        model perfomance!!! (default: 1536)
  --compute_type {default,auto,int8,int8_float16,int8_float32,int8_bfloat16,int16,float16,float32,bfloat16}, -ct {default,auto,int8,int8_float16,int8_float32,int8_bfloat16,int16,float16,float32,bfloat16}
                        Type of quantization to use (see https://opennmt.net/CTranslate2/quantization.html). (default:
                        int8_float32)
  --batch_recursive, -br
                        Enables recursive batch processing. Note: If set then it changes defaults of --output_dir.
                        (default: False)
  --beep_off            Disables beep sound when operation is finished. (default: False)
  --skip                Skips files if 'srt' subtitle exists. Works if input is wildcard or directory. (default:
                        False)
  --checkcuda, -cc      Returns CUDA device count. (for Subtitle Edit's internal use)
  --print_progress, -pp
                        Prints progress bar instead of transcription. (default: False)
```

**Comment by Purfview** [comment]
> Then I try switches --verify=false and --requests_verify=false, does not work

There are no such args.
